/** Representative integration names for landing visual (full catalogue: 706). */
export const CONNECTOR_TOTAL = 706;

export const FEATURED_TOOLS = [
  'Slack',
  'GitHub',
  'Gmail',
  'Linear',
  'Notion',
  'Stripe',
  'Twilio',
  'Salesforce',
  'HubSpot',
  'Jira',
  'Asana',
  'Figma',
  'Zoom',
  'Discord',
  'Airtable',
  'Shopify',
  'Intercom',
  'Zendesk',
  'Dropbox',
  'Google Drive',
  'Microsoft Teams',
  'Outlook',
  'Cal.com',
  'Freshdesk',
  'Monday.com',
  'Trello',
  'ClickUp',
  'PagerDuty',
  'Datadog',
  'Sentry',
  'Postgres',
  'Redis',
  'MongoDB',
  'Snowflake',
  'Databricks',
  'AWS',
  'OpenAI',
  'Anthropic',
  'Groq',
  'Supabase',
  'Firebase',
  'Vercel',
  'Netlify',
  'Cloudflare',
  'Mailchimp',
  'SendGrid',
  'Typeform',
  'Miro',
  'Loom',
  'Confluence',
  'Bitbucket',
  'GitLab',
  'CircleCI',
  'Docker',
  'Kubernetes',
  'Amplitude',
  'Mixpanel',
  'Segment',
  'QuickBooks',
  'Xero',
  'Workday',
  'Greenhouse',
  'DocuSign',
  'Box',
  'Pipedrive',
  'ServiceNow',
  'Okta',
  'Auth0',
  'Plaid',
  'Square',
  'PayPal',
  'Deel',
  'Rippling',
  'Tableau',
  'Looker',
  'Metabase',
  'Retool',
  'Zapier',
  'Make',
  'n8n',
  'Activepieces',
  'Temporal',
  'Kafka',
  'Elasticsearch',
  'Neo4j',
  'Hugging Face',
  'Replicate',
  'Cohere',
  'Mistral',
  'Pinecone',
  'Nango',
  'Fivetran',
  'Airbyte',
  'dbt',
  'Airflow',
  'LaunchDarkly',
  'Statsig',
  'PostHog',
  'Customer.io',
  'Braze',
  'Klaviyo',
  'Buffer',
  'Hootsuite',
  'LinkedIn',
  'Twitter/X',
  'YouTube',
  'Spotify',
  'Calendly',
  'Product Hunt',
  'Hacker News',
  'Raycast',
  'Obsidian',
  'Grammarly',
  'Webflow',
  'Contentful',
  'Sanity',
  'Strapi',
  'Prismic',
  'Algolia',
  'Meilisearch',
  'PlanetScale',
  'Neon',
  'BigQuery',
  'Redshift',
  'Snowpipe',
  'RabbitMQ',
  'Pusher',
  'Ably',
  'Stream',
  'Gong',
  'Outreach',
  'Salesloft',
  'Apollo.io',
  'ZoomInfo',
  'Unbounce',
  'Chargebee',
  'Recurly',
  'Adyen',
  'Braintree',
  'Checkout.com',
  'Klarna',
  'Mercury',
  'Ramp',
  'Brex',
  'Lattice',
  'Notion AI',
  'Stability AI',
  'Midjourney',
  'Photoroom',
  'Binance',
  'Coinbase',
  'Twilio SendGrid',
  'Resend',
  'Loops',
  'ConvertKit',
  'Substack',
  'Ghost',
  'Webex',
  'Gather',
  'Freshservice',
  'Freshsales',
  'Teamwork',
  'Shortcut',
  'Productboard',
  'Hotjar',
  'FullStory',
  'LogRocket',
  'Heap',
  'Optimizely',
  'VWO',
  'Instapage',
  'Leadpages',
  'Gumroad',
  'Paddle',
  'Lemon Squeezy',
  'Modern Treasury',
  'Finicity',
  'Yodlee',
  'Merge',
  'Apideck',
  'Paragon',
  'Tray.io',
  'Workato',
  'MuleSoft',
  'Prefect',
  'Dagster',
  'MLflow',
  'Weights & Biases',
  'Labelbox',
  'Scale AI',
  'Together AI',
  'Perplexity',
  'Qdrant',
  'Chroma',
  'Upstash',
  'CockroachDB',
  'ClickHouse',
  'DuckDB',
  'Confluent',
  'Redpanda',
  'NATS',
  'Socket.io',
  'Vonage',
  'MessageBird',
  'RingCentral',
  'Aircall',
  'Gong.io',
  'Clari',
  '6sense',
  'Demandbase',
  'Mutiny',
  'Metadata',
  'Copy.ai',
  'Jasper',
  'Writer',
  'Tally',
  'Jotform',
  'SurveyMonkey',
  'Smartsheet',
  'Basecamp',
  'Height',
  'Buildkite',
  'Heroku',
  'Railway',
  'Fly.io',
  'Render',
  'DigitalOcean',
  'Prometheus',
  'Grafana',
  'Loki',
  'Jaeger',
  'New Relic',
  'Splunk',
  'Elastic',
  'Kibana',
  'Vault',
  'Consul',
  'Permit.io',
  'WorkOS',
  'Clerk',
  'Stytch',
  'Magic Link',
  'Keycloak',
  'Cognito',
  'Hunter',
  'Attio',
  'Clearbit',
  'Lusha',
  'Cognism',
  'Devin',
  'Granola',
  'Instabase',
  'Amazon SQS',
  'Couchbase',
  'Matomo',
  'Stability',
  'Motion',
  'Mem',
  'Timelines AI',
  'Vadoo AI',
  'Air Ops',
  'Image Router',
  'ModelsLab',
  'Instantly',
  'Campaign Monitor',
  'AppFollow',
  'Giftbit',
  'VLM Run',
  'Omni Co',
  'Metatext',
  'Plunk',
  'Buffer Analyze',
  'Brandwatch',
  'Meltwater',
  'PR Newswire',
  'BetaList',
  'Indie Hackers',
  'Dev.to',
  'Hashnode',
  'Beehiiv',
  'OptinMonster',
  'OneSignal',
  'Pushwoosh',
  'CleverTap',
  'MoEngage',
  'Insider',
  'Bloomreach',
  'Dynamic Yield',
  'GrowthBook',
  'Eppo',
  'ConfigCat',
  'Flagsmith',
  'Unleash',
  'Intellimize',
  'Nosto',
  'Swarm',
  'Particle',
] as const;

export function toolLayoutSeed(index: number): {
  x: number;
  y: number;
  delay: number;
  size: 'sm' | 'md' | 'lg';
} {
  const s = Math.sin(index * 12.9898 + 78.233) * 43758.5453;
  const r = s - Math.floor(s);
  const r2 = Math.sin(index * 93.989 + 12.233) * 12758.5453;
  const r3 = r2 - Math.floor(r2);
  return {
    x: r * 100,
    y: r3 * 100,
    delay: (index % 20) * 0.05,
    size: index % 7 === 0 ? 'lg' : index % 3 === 0 ? 'md' : 'sm',
  };
}
